export const LOADING = 'LOADING';

export const GRID_STATE_CHANGE = 'GRID_STATE_CHANGE';
export const GRID_ADD_METADATA = 'GRID_ADD_METADATA';
export const GRID_ADD_DEPENDENCIES = 'GRID_ADD_DEPENDENCIES';
export const GRID_REMOVE_FROM_SELECTION = 'GRID_REMOVE_FROM_SELECTION';

export const GET_USER_BLACKLIST = 'GET_USER_BLACKLIST';
export const UPDATE_USER_BLACKLIST = 'UPDATE_USER_BLACKLIST';

export const SETTINGS_ORG_UNIT_CHILDREN = 'SETTINGS_ORG_UNIT_CHILDREN';
export const SETTINGS_USER_CLEAN_UP = 'SETTINGS_USER_CLEAN_UP';